---
- name: Deploy Scientific Calculator
  # We target 'localhost' since we're deploying on the Jenkins agent itself
  hosts: localhost
  connection: local
  gather_facts: no

  # These variables will be passed in from the Jenkins command
  vars:
    docker_username: "salvoslayer"
    app_image_name: "scientific-calculator"
    host_port: 8081
    container_port: 8080

  tasks:
    - name: Deploy or Redeploy the container
      # This single, idempotent task replaces 'docker stop', 'docker rm', and 'docker run'
      community.docker.docker_container:
        name: "{{ app_image_name }}"
        image: "{{ docker_username }}/{{ app_image_name }}:latest"
        state: started
        pull: yes # Always pull the 'latest' tag from the registry
        recreate: yes # This is key: it stops/removes the old container if it exists
        ports:
          - "{{ host_port }}:{{ container_port }}"
